version: "2"

services:
  eureka:
    container_name: heynow-eureka
    image: io.heynow.eureka:latest
    ports:
      - "9000:9000"
    networks:
      - heynow

  config:
    container_name: heynow-config
    image: io.heynow.configserver:latest
    expose:
      - "8888"
    environment:
      - spring.cloud.config.server.git.uri=https://github.com/ciffer/heynow-config-test.git
      - eureka.client.serviceUrl.defaultZone=http://eureka:9000/eureka
    depends_on:
      - eureka
    networks:
      - heynow

  edge:
    container_name: heynow-edge
    image: io.heynow.heynow-edge:latest
    ports:
      - "8081:8081"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:9000/eureka
    depends_on:
          - eureka
          - config
    networks:
      - heynow

networks:
  heynow: