version: "2"

services:
  db_volume:
    container_name: heynow-db-volume
    image: postgres:latest
    volumes:
      - /opt/heynow/data:/var/lib/postgresql/data
    command: /bin/true

  db:
    container_name: heynow-db
    image: postgres:latest
    volumes_from:
      - db_volume
    environment:
      - POSTGRES_PASSWORD=ocado
    networks:
      - heynow
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    networks:
      - heynow
      
  eureka:
    container_name: heynow-eureka
    image: heynow/eureka:latest
    ports:
      - "9000:9000"
    networks:
      - heynow

  config:
    container_name: heynow-config
    image: heynow/configserver:latest
    ports:
      - "8888:8888"
    environment:
      - spring.cloud.config.server.git.uri=https://github.com/heynow-io/heynow-config.git
      - eureka.client.serviceUrl.defaultZone=http://eureka:9000/eureka
    depends_on:
      - eureka
    networks:
      - heynow

  shephard:
    container_name: heynow-shephard
    image: heynow/shephard:latest
    ports:
      - "9999:8080"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:9000/eureka
      - spring.cloud.config.uri=http://config:8888
    depends_on:
          - eureka
          - config
    networks:
      - heynow
      
  stream-manager:
    container_name: heynow-stream-manager
    image: heynow/stream-manager:latest
    ports:
      - "8082:8080"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:9000/eureka
      - spring.cloud.config.uri=http://config:8888
    depends_on:
      - eureka
      - config
      - db
    networks:
      - heynow
      
  event-source:
    container_name: heynow-event-source
    image: heynow/event-source:latest
    ports:
      - "8083:8080"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:9000/eureka
      - spring.cloud.config.uri=http://config:8888
    depends_on:
      - eureka
      - config
    networks:
      - heynow
      
  edge:
    container_name: heynow-edge
    image: heynow/edge:latest
    ports:
      - "8081:8081"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:9000/eureka
    depends_on:
          - eureka
          - config
    networks:
      - heynow

networks:
  heynow:
